services:
    ac_marche_prefix.example:
        class: AcMarche\PrefixBundle\Subscriber\TablePrefixSubscriber
        arguments: ["%database_table_prefix%"]
        tags:
            - { name: doctrine.event_subscriber }
